namespace Yura.App.Localization;

/// <summary>
/// The string table for every language Yura ships.
/// </summary>
/// <remarks>
/// Held in code rather than in .resx so that the two languages sit side by side and a
/// missing translation is a compile-time-visible gap in one table rather than a silent
/// fallback. Chinese strings are kept close to the English in meaning but not in length;
/// checking that the layout survives the difference is an explicit acceptance criterion.
/// </remarks>
internal static class Strings
{
    public static string Lookup(string language, string key)
    {
        var table = language.StartsWith("zh", StringComparison.OrdinalIgnoreCase) ? ZhHans : English;
        if (table.TryGetValue(key, out var value))
        {
            return value;
        }

        // Fall back to English before giving up, so a partially translated build degrades
        // to a readable UI rather than to placeholder noise.
        return English.TryGetValue(key, out var fallback) ? fallback : $"«{key}»";
    }

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        // -- shell ----------------------------------------------------------
        ["App.Name"] = "Yura",
        ["Nav.Processes"] = "Processes",
        ["Nav.Games"] = "Games",
        ["Nav.Connections"] = "Connections",
        ["Nav.Proxies"] = "Proxies",
        ["Nav.Rules"] = "Rules",
        ["Nav.Diagnostics"] = "Diagnostics",
        ["Nav.Settings"] = "Settings",
        ["Shell.DaemonConnected"] = "Daemon connected",
        ["Shell.DaemonDisconnected"] = "Daemon not connected",
        ["Shell.DaemonDisconnectedDetail"] = "Routing changes cannot be applied until the daemon is running.",
        ["Shell.Reconnect"] = "Reconnect",

        // -- common ---------------------------------------------------------
        ["Common.Apply"] = "Apply",
        ["Common.Cancel"] = "Cancel",
        ["Common.Save"] = "Save",
        ["Common.Close"] = "Close",
        ["Common.Refresh"] = "Refresh",
        ["Common.Search"] = "Search",
        ["Common.Remove"] = "Remove",
        ["Common.Undo"] = "Undo",
        ["Common.Test"] = "Test",
        ["Common.Details"] = "Technical details",
        ["Common.Copy"] = "Copy",
        ["Common.Unavailable"] = "Unavailable",
        ["Common.NotMeasured"] = "Not measured",
        ["Common.Unknown"] = "Unknown",
        ["Common.Pending"] = "Pending",
        ["Common.Loading"] = "Loading…",
        ["Common.Pause"] = "Pause updates",
        ["Common.Resume"] = "Resume updates",
        ["Common.Paused"] = "Updates paused",

        // -- processes page -------------------------------------------------
        ["Processes.Title"] = "Processes",
        ["Processes.Subtitle"] = "Select a running application and route its traffic through a proxy.",
        ["Processes.SearchPlaceholder"] = "Search by name, path, PID or user",
        ["Processes.TreeView"] = "Process tree",
        ["Processes.FlatView"] = "Flat list",
        ["Processes.ShowSystem"] = "Include system processes",
        ["Processes.Column.Process"] = "Process",
        ["Processes.Column.Pid"] = "PID",
        ["Processes.Column.User"] = "User",
        ["Processes.Column.Path"] = "Executable path",
        ["Processes.Column.Parent"] = "Parent",
        ["Processes.Column.Policy"] = "Routing policy",
        ["Processes.Column.Connections"] = "Conns",
        ["Processes.Empty"] = "No process matches this filter.",
        ["Processes.EmptyHint"] = "Clear the search box or include system processes.",
        ["Processes.Selected"] = "{0} selected",
        ["Processes.LiveSorting"] = "Live sorting",
        ["Processes.Count"] = "{0} processes",
        ["Processes.CountFiltered"] = "{0} of {1} processes",

        ["Processes.Action.ProxyInstance"] = "Proxy this instance",
        ["Processes.Action.AlwaysProxy"] = "Always proxy this executable",
        ["Processes.Action.Direct"] = "Route directly",
        ["Processes.Action.Block"] = "Block network access",
        ["Processes.Action.RemoveOverride"] = "Remove override",
        ["Processes.Action.IncludeChildren"] = "Include child processes",
        ["Processes.Action.InspectConnections"] = "Inspect connections",

        ["Processes.Scope.Title"] = "Rule scope",
        ["Processes.Scope.Instance"] = "This running instance",
        ["Processes.Scope.InstanceHint"] = "Ends when this process exits. A reused PID never inherits it.",
        ["Processes.Scope.Executable"] = "Future instances of this executable",
        ["Processes.Scope.ExecutableHint"] = "Saved and reapplied whenever this path runs again.",
        ["Processes.Scope.Tree"] = "This process and its children",
        ["Processes.Scope.TreeHint"] = "New children are covered. Existing children keep their current route.",

        ["Processes.Inspector.Identity"] = "Identity",
        ["Processes.Inspector.Policy"] = "Current policy",
        ["Processes.Inspector.Connections"] = "Active connections",
        ["Processes.Inspector.Actions"] = "Actions",
        ["Processes.Inspector.Route"] = "Route to",
        ["Processes.Inspector.NoSelection"] = "Select a process to inspect it.",
        ["Processes.Inspector.StartTime"] = "Started",
        ["Processes.Inspector.Cgroup"] = "Control group",
        ["Processes.Inspector.WineTarget"] = "Wine target",

        ["Processes.Policy.Direct"] = "Direct",
        ["Processes.Policy.Blocked"] = "Blocked",
        ["Processes.Policy.Proxied"] = "Proxied",
        ["Processes.Policy.PendingApply"] = "Applying…",
        ["Processes.Policy.NewConnectionsOnly"] = "New connections only",

        ["Processes.Applied.Title"] = "Rule active for new connections",
        ["Processes.Applied.Body"] =
            "Connections opened from now on use {0}. Connections that were already open keep their previous route until the application reconnects.",
        ["Processes.PathDenied"] = "Permission denied",
        ["Processes.PathDeleted"] = "Executable replaced since start",

        // -- games page -----------------------------------------------------
        ["Games.Title"] = "Games",
        ["Games.Subtitle"] = "Pick a game, choose a route, and start acceleration.",
        ["Games.SelectGame"] = "Game",
        ["Games.SelectRoute"] = "Route",
        ["Games.StartBoost"] = "Start boost",
        ["Games.StopBoost"] = "Stop boost",
        ["Games.Comparison"] = "Direct vs routed",
        ["Games.Direct"] = "Direct",
        ["Games.Routed"] = "Routed",
        ["Games.Latency"] = "Latency",
        ["Games.Jitter"] = "Jitter",
        ["Games.Loss"] = "Packet loss",
        ["Games.MeasurementTarget"] = "Measured against",
        ["Games.LastUpdate"] = "Last updated",
        ["Games.SessionDuration"] = "Session time",
        ["Games.Compatibility"] = "Transport support",
        ["Games.TcpSupported"] = "TCP supported",
        ["Games.UdpSupported"] = "UDP supported",
        ["Games.UdpUnsupported"] = "UDP not supported",
        ["Games.UdpUnknown"] = "UDP not measured",
        ["Games.UdpWarning"] = "This proxy cannot relay UDP. Games that use UDP will not be accelerated.",
        ["Games.NoGames"] = "No games detected yet.",
        ["Games.NoGamesHint"] = "Add a game manually, or start one and it will appear here.",

        ["Games.State.Ready"] = "Ready",
        ["Games.State.Testing"] = "Testing",
        ["Games.State.Starting"] = "Starting",
        ["Games.State.WaitingForGame"] = "Waiting for game",
        ["Games.State.Routing"] = "Routing",
        ["Games.State.Degraded"] = "Degraded",
        ["Games.State.Stopping"] = "Stopping",
        ["Games.State.Failed"] = "Failed",

        // -- proxy editor ---------------------------------------------------
        ["Proxy.Editor.TitleNew"] = "Add proxy",
        ["Proxy.Editor.TitleEdit"] = "Edit proxy",
        ["Proxy.Name"] = "Display name",
        ["Proxy.NamePlaceholder"] = "Home server",
        ["Proxy.Protocol"] = "Protocol",
        ["Proxy.Host"] = "Host",
        ["Proxy.HostPlaceholder"] = "127.0.0.1 or proxy.example.com",
        ["Proxy.Port"] = "Port",
        ["Proxy.Username"] = "Username",
        ["Proxy.Password"] = "Password",
        ["Proxy.Optional"] = "Optional",
        ["Proxy.Advanced"] = "Advanced options",
        ["Proxy.AdvancedHint"] = "Timeouts, TLS verification and UDP behaviour.",
        ["Proxy.TestConnection"] = "Test connection",
        ["Proxy.Testing"] = "Testing…",
        ["Proxy.TestPassed"] = "Reachable in {0} ms",
        ["Proxy.TestFailed"] = "Could not reach the proxy",
        ["Proxy.Hint"] = "Yura does not run a proxy for you. Point it at one you already run.",

        ["Proxy.Validation.NameRequired"] = "Enter a name so you can recognise this proxy.",
        ["Proxy.Validation.NameDuplicate"] = "Another proxy already uses this name.",
        ["Proxy.Validation.HostRequired"] = "Enter the host name or IP address of the proxy.",
        ["Proxy.Validation.HostInvalid"] = "This is not a valid host name or IP address.",
        ["Proxy.Validation.PortRange"] = "Port must be between 1 and 65535.",

        // -- connections ----------------------------------------------------
        ["Connections.Route.Direct"] = "Direct",
        ["Connections.Route.Proxied"] = "Proxied",
        ["Connections.Route.Blocked"] = "Blocked",
        ["Connections.Route.Previous"] = "Previous route",
        ["Connections.Route.PreviousHint"] =
            "Opened before the rule was applied. Restart the application to move it onto the proxy.",
    };

    private static readonly Dictionary<string, string> ZhHans = new(StringComparer.Ordinal)
    {
        ["App.Name"] = "Yura",
        ["Nav.Processes"] = "进程",
        ["Nav.Games"] = "游戏",
        ["Nav.Connections"] = "连接",
        ["Nav.Proxies"] = "代理",
        ["Nav.Rules"] = "规则",
        ["Nav.Diagnostics"] = "诊断",
        ["Nav.Settings"] = "设置",
        ["Shell.DaemonConnected"] = "守护进程已连接",
        ["Shell.DaemonDisconnected"] = "守护进程未连接",
        ["Shell.DaemonDisconnectedDetail"] = "守护进程运行前无法应用路由更改。",
        ["Shell.Reconnect"] = "重新连接",

        ["Common.Apply"] = "应用",
        ["Common.Cancel"] = "取消",
        ["Common.Save"] = "保存",
        ["Common.Close"] = "关闭",
        ["Common.Refresh"] = "刷新",
        ["Common.Search"] = "搜索",
        ["Common.Remove"] = "移除",
        ["Common.Undo"] = "撤销",
        ["Common.Test"] = "测试",
        ["Common.Details"] = "技术细节",
        ["Common.Copy"] = "复制",
        ["Common.Unavailable"] = "不可用",
        ["Common.NotMeasured"] = "未测量",
        ["Common.Unknown"] = "未知",
        ["Common.Pending"] = "等待中",
        ["Common.Loading"] = "加载中…",
        ["Common.Pause"] = "暂停更新",
        ["Common.Resume"] = "恢复更新",
        ["Common.Paused"] = "更新已暂停",

        ["Processes.Title"] = "进程",
        ["Processes.Subtitle"] = "选择正在运行的应用程序，并将其流量通过代理转发。",
        ["Processes.SearchPlaceholder"] = "按名称、路径、PID 或用户搜索",
        ["Processes.TreeView"] = "进程树",
        ["Processes.FlatView"] = "平铺列表",
        ["Processes.ShowSystem"] = "包含系统进程",
        ["Processes.Column.Process"] = "进程",
        ["Processes.Column.Pid"] = "PID",
        ["Processes.Column.User"] = "用户",
        ["Processes.Column.Path"] = "可执行文件路径",
        ["Processes.Column.Parent"] = "父进程",
        ["Processes.Column.Policy"] = "路由策略",
        ["Processes.Column.Connections"] = "连接数",
        ["Processes.Empty"] = "没有符合此筛选条件的进程。",
        ["Processes.EmptyHint"] = "请清除搜索框，或包含系统进程。",
        ["Processes.Selected"] = "已选择 {0} 项",
        ["Processes.LiveSorting"] = "实时排序",
        ["Processes.Count"] = "{0} 个进程",
        ["Processes.CountFiltered"] = "{0} / {1} 个进程",

        ["Processes.Action.ProxyInstance"] = "代理此实例",
        ["Processes.Action.AlwaysProxy"] = "始终代理此可执行文件",
        ["Processes.Action.Direct"] = "直接连接",
        ["Processes.Action.Block"] = "阻止网络访问",
        ["Processes.Action.RemoveOverride"] = "移除临时覆盖",
        ["Processes.Action.IncludeChildren"] = "包含子进程",
        ["Processes.Action.InspectConnections"] = "查看连接",

        ["Processes.Scope.Title"] = "规则范围",
        ["Processes.Scope.Instance"] = "此运行实例",
        ["Processes.Scope.InstanceHint"] = "该进程退出后规则失效。重用的 PID 不会继承此策略。",
        ["Processes.Scope.Executable"] = "此可执行文件的后续实例",
        ["Processes.Scope.ExecutableHint"] = "已保存，此路径再次运行时会重新应用。",
        ["Processes.Scope.Tree"] = "此进程及其子进程",
        ["Processes.Scope.TreeHint"] = "新建子进程会被覆盖。已有子进程保持当前路由。",

        ["Processes.Inspector.Identity"] = "标识",
        ["Processes.Inspector.Policy"] = "当前策略",
        ["Processes.Inspector.Connections"] = "活动连接",
        ["Processes.Inspector.Actions"] = "操作",
        ["Processes.Inspector.Route"] = "路由至",
        ["Processes.Inspector.NoSelection"] = "选择一个进程以查看详情。",
        ["Processes.Inspector.StartTime"] = "启动于",
        ["Processes.Inspector.Cgroup"] = "控制组",
        ["Processes.Inspector.WineTarget"] = "Wine 目标",

        ["Processes.Policy.Direct"] = "直连",
        ["Processes.Policy.Blocked"] = "已阻止",
        ["Processes.Policy.Proxied"] = "已代理",
        ["Processes.Policy.PendingApply"] = "正在应用…",
        ["Processes.Policy.NewConnectionsOnly"] = "仅新建连接",

        ["Processes.Applied.Title"] = "规则已对新连接生效",
        ["Processes.Applied.Body"] = "此后建立的连接将使用 {0}。已经打开的连接在应用程序重新连接之前仍使用原有路由。",
        ["Processes.PathDenied"] = "权限不足",
        ["Processes.PathDeleted"] = "启动后可执行文件已被替换",

        ["Games.Title"] = "游戏",
        ["Games.Subtitle"] = "选择游戏，选定线路，然后开始加速。",
        ["Games.SelectGame"] = "游戏",
        ["Games.SelectRoute"] = "线路",
        ["Games.StartBoost"] = "开始加速",
        ["Games.StopBoost"] = "停止加速",
        ["Games.Comparison"] = "直连与代理对比",
        ["Games.Direct"] = "直连",
        ["Games.Routed"] = "代理",
        ["Games.Latency"] = "延迟",
        ["Games.Jitter"] = "抖动",
        ["Games.Loss"] = "丢包率",
        ["Games.MeasurementTarget"] = "测量目标",
        ["Games.LastUpdate"] = "最后更新",
        ["Games.SessionDuration"] = "会话时长",
        ["Games.Compatibility"] = "传输协议支持",
        ["Games.TcpSupported"] = "支持 TCP",
        ["Games.UdpSupported"] = "支持 UDP",
        ["Games.UdpUnsupported"] = "不支持 UDP",
        ["Games.UdpUnknown"] = "UDP 未测量",
        ["Games.UdpWarning"] = "此代理无法转发 UDP。使用 UDP 的游戏将不会被加速。",
        ["Games.NoGames"] = "尚未检测到游戏。",
        ["Games.NoGamesHint"] = "可手动添加游戏，或启动游戏后它会显示在此处。",

        ["Games.State.Ready"] = "就绪",
        ["Games.State.Testing"] = "测试中",
        ["Games.State.Starting"] = "启动中",
        ["Games.State.WaitingForGame"] = "等待游戏",
        ["Games.State.Routing"] = "加速中",
        ["Games.State.Degraded"] = "质量下降",
        ["Games.State.Stopping"] = "正在停止",
        ["Games.State.Failed"] = "失败",

        ["Proxy.Editor.TitleNew"] = "添加代理",
        ["Proxy.Editor.TitleEdit"] = "编辑代理",
        ["Proxy.Name"] = "显示名称",
        ["Proxy.NamePlaceholder"] = "家庭服务器",
        ["Proxy.Protocol"] = "协议",
        ["Proxy.Host"] = "主机",
        ["Proxy.HostPlaceholder"] = "127.0.0.1 或 proxy.example.com",
        ["Proxy.Port"] = "端口",
        ["Proxy.Username"] = "用户名",
        ["Proxy.Password"] = "密码",
        ["Proxy.Optional"] = "可选",
        ["Proxy.Advanced"] = "高级选项",
        ["Proxy.AdvancedHint"] = "超时、TLS 校验与 UDP 行为。",
        ["Proxy.TestConnection"] = "测试连接",
        ["Proxy.Testing"] = "测试中…",
        ["Proxy.TestPassed"] = "可达，用时 {0} 毫秒",
        ["Proxy.TestFailed"] = "无法连接到代理",
        ["Proxy.Hint"] = "Yura 不会为你运行代理，请指向你已在运行的代理。",

        ["Proxy.Validation.NameRequired"] = "请输入名称，以便识别此代理。",
        ["Proxy.Validation.NameDuplicate"] = "已有同名代理。",
        ["Proxy.Validation.HostRequired"] = "请输入代理的主机名或 IP 地址。",
        ["Proxy.Validation.HostInvalid"] = "这不是有效的主机名或 IP 地址。",
        ["Proxy.Validation.PortRange"] = "端口必须介于 1 与 65535 之间。",

        ["Connections.Route.Direct"] = "直连",
        ["Connections.Route.Proxied"] = "已代理",
        ["Connections.Route.Blocked"] = "已阻止",
        ["Connections.Route.Previous"] = "原有路由",
        ["Connections.Route.PreviousHint"] = "在规则应用之前建立。重启应用程序即可改用代理。",
    };
}
