namespace Yura.App.Localization;

/// <summary>
/// The string table for every language Yura ships.
/// </summary>
/// <remarks>
/// Held in code rather than in .resx so that the two languages sit side by side and a
/// missing translation is a compile-time-visible gap in one table rather than a silent
/// fallback. Chinese strings are kept close to the English in meaning but not in length;
/// checking that the layout survives the difference is an explicit acceptance criterion.
/// </remarks>
internal static class Strings
{
    public static string Lookup(string language, string key)
    {
        var table = language.StartsWith("zh", StringComparison.OrdinalIgnoreCase) ? ZhHans : English;
        if (table.TryGetValue(key, out var value))
        {
            return value;
        }

        // Fall back to English before giving up, so a partially translated build degrades
        // to a readable UI rather than to placeholder noise.
        return English.TryGetValue(key, out var fallback) ? fallback : $"«{key}»";
    }

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        // -- shell ----------------------------------------------------------
        ["App.Name"] = "Yura",
        ["Nav.Processes"] = "Processes",
        ["Nav.Games"] = "Games",
        ["Nav.Connections"] = "Connections",
        ["Nav.Proxies"] = "Proxies",
        ["Nav.Rules"] = "Rules",
        ["Nav.Diagnostics"] = "Diagnostics",
        ["Nav.Settings"] = "Settings",
        ["Shell.DaemonConnected"] = "Daemon connected",
        ["Shell.DaemonDisconnected"] = "Daemon not connected",
        ["Shell.DaemonDisconnectedDetail"] = "Routing changes cannot be applied until the daemon is running.",
        ["Shell.Reconnect"] = "Reconnect",

        // -- common ---------------------------------------------------------
        ["Common.Apply"] = "Apply",
        ["Common.Cancel"] = "Cancel",
        ["Common.Save"] = "Save",
        ["Common.Close"] = "Close",
        ["Common.Refresh"] = "Refresh",
        ["Common.Search"] = "Search",
        ["Common.Remove"] = "Remove",
        ["Common.Undo"] = "Undo",
        ["Common.Test"] = "Test",
        ["Common.Details"] = "Technical details",
        ["Common.Copy"] = "Copy",
        ["Common.Unavailable"] = "Unavailable",
        ["Common.NotMeasured"] = "Not measured",
        ["Common.Unknown"] = "Unknown",
        ["Common.Pending"] = "Pending",
        ["Common.Loading"] = "Loading…",
        ["Common.Pause"] = "Pause updates",
        ["Common.Resume"] = "Resume updates",
        ["Common.Paused"] = "Updates paused",

        // -- processes page -------------------------------------------------
        ["Processes.Title"] = "Processes",
        ["Processes.Subtitle"] = "Select a running application and route its traffic through a proxy.",
        ["Processes.SearchPlaceholder"] = "Search by name, path, PID or user",
        ["Processes.TreeView"] = "Process tree",
        ["Processes.FlatView"] = "Flat list",
        ["Processes.ShowSystem"] = "Include system processes",
        ["Processes.Column.Process"] = "Process",
        ["Processes.Column.Pid"] = "PID",
        ["Processes.Column.User"] = "User",
        ["Processes.Column.Path"] = "Executable path",
        ["Processes.Column.Parent"] = "Parent",
        ["Processes.Column.Policy"] = "Routing policy",
        ["Processes.Column.Connections"] = "Conns",
        ["Processes.Empty"] = "No process matches this filter.",
        ["Processes.EmptyHint"] = "Clear the search box or include system processes.",
        ["Processes.Selected"] = "{0} selected",
        ["Processes.LiveSorting"] = "Live sorting",
        ["Processes.Count"] = "{0} processes",
        ["Processes.CountFiltered"] = "{0} of {1} processes",

        ["Processes.Action.ProxyInstance"] = "Proxy this instance",
        ["Processes.Action.AlwaysProxy"] = "Always proxy this executable",
        ["Processes.Action.Direct"] = "Route directly",
        ["Processes.Action.Block"] = "Block network access",
        ["Processes.Action.RemoveOverride"] = "Remove override",
        ["Processes.Action.IncludeChildren"] = "Include child processes",
        ["Processes.Action.InspectConnections"] = "Inspect connections",

        ["Processes.Scope.Title"] = "Rule scope",
        ["Processes.Scope.Instance"] = "This running instance",
        ["Processes.Scope.InstanceHint"] = "Ends when this process exits. A reused PID never inherits it.",
        ["Processes.Scope.Executable"] = "Future instances of this executable",
        ["Processes.Scope.ExecutableHint"] = "Saved and reapplied whenever this path runs again.",
        ["Processes.Scope.Tree"] = "This process and its children",
        ["Processes.Scope.TreeHint"] = "New children are covered. Existing children keep their current route.",

        ["Processes.Inspector.Identity"] = "Identity",
        ["Processes.Inspector.Policy"] = "Current policy",
        ["Processes.Inspector.Connections"] = "Active connections",
        ["Processes.Inspector.Actions"] = "Actions",
        ["Processes.Inspector.Route"] = "Route to",
        ["Processes.Inspector.NoSelection"] = "Select a process to inspect it.",
        ["Processes.Inspector.StartTime"] = "Started",
        ["Processes.Inspector.Cgroup"] = "Control group",
        ["Processes.Inspector.WineTarget"] = "Wine target",

        ["Processes.Policy.Direct"] = "Direct",
        ["Processes.Policy.Blocked"] = "Blocked",
        ["Processes.Policy.Proxied"] = "Proxied",
        ["Processes.Policy.PendingApply"] = "Applying…",
        ["Processes.Policy.NewConnectionsOnly"] = "New connections only",

        ["Processes.Applied.Title"] = "Rule active for new connections",
        ["Processes.Applied.Body"] =
            "Connections opened from now on use {0}. Connections that were already open keep their previous route until the application reconnects.",
        ["Processes.PathDenied"] = "Permission denied",
        ["Processes.PathDeleted"] = "Executable replaced since start",

        // -- games page -----------------------------------------------------
        ["Games.Title"] = "Games",
        ["Games.Subtitle"] = "Pick a game, choose a route, and start acceleration.",
        ["Games.SelectGame"] = "Game",
        ["Games.SelectRoute"] = "Route",
        ["Games.StartBoost"] = "Start boost",
        ["Games.StopBoost"] = "Stop boost",
        ["Games.Comparison"] = "Direct vs routed",
        ["Games.Direct"] = "Direct",
        ["Games.Routed"] = "Routed",
        ["Games.Latency"] = "Latency",
        ["Games.Jitter"] = "Jitter",
        ["Games.Loss"] = "Packet loss",
        ["Games.MeasurementTarget"] = "Measured against",
        ["Games.LastUpdate"] = "Last updated",
        ["Games.SessionDuration"] = "Session time",
        ["Games.Compatibility"] = "Transport support",
        ["Games.TcpSupported"] = "TCP supported",
        ["Games.UdpSupported"] = "UDP supported",
        ["Games.UdpUnsupported"] = "UDP not supported",
        ["Games.UdpUnknown"] = "UDP not measured",
        ["Games.UdpWarning"] = "This proxy cannot relay UDP. Games that use UDP will not be accelerated.",
        ["Games.NoGames"] = "No games detected yet.",
        ["Games.NoGamesHint"] = "Add a game manually, or start one and it will appear here.",

        ["Games.SessionState"] = "Session state",
        ["Games.State.Ready"] = "Ready",
        ["Games.State.Testing"] = "Testing",
        ["Games.State.Starting"] = "Starting",
        ["Games.State.WaitingForGame"] = "Waiting for game",
        ["Games.State.Routing"] = "Routing",
        ["Games.State.Degraded"] = "Degraded",
        ["Games.State.Stopping"] = "Stopping",
        ["Games.State.Failed"] = "Failed",

        // -- proxy editor ---------------------------------------------------
        ["Proxy.Editor.TitleNew"] = "Add proxy",
        ["Proxy.Editor.TitleEdit"] = "Edit proxy",
        ["Proxy.Name"] = "Display name",
        ["Proxy.NamePlaceholder"] = "Home server",
        ["Proxy.Protocol"] = "Protocol",
        ["Proxy.Host"] = "Host",
        ["Proxy.HostPlaceholder"] = "127.0.0.1 or proxy.example.com",
        ["Proxy.Port"] = "Port",
        ["Proxy.Username"] = "Username",
        ["Proxy.Password"] = "Password",
        ["Proxy.Optional"] = "Optional",
        ["Proxy.Advanced"] = "Advanced options",
        ["Proxy.AdvancedHint"] = "Timeouts, TLS verification and UDP behaviour.",
        ["Proxy.TestConnection"] = "Test connection",
        ["Proxy.Testing"] = "Testing…",
        ["Proxy.TestPassed"] = "Reachable in {0} ms",
        ["Proxy.TestFailed"] = "Could not reach the proxy",
        ["Proxy.Hint"] = "Yura does not run a proxy for you. Point it at one you already run.",
        ["Proxy.SecretHint"] = "The password is saved in {0}, never in the configuration file.",
        ["Proxy.SecretHintUnavailable"] =
            "No desktop secret service was found, so the password is kept for this session only. It is never written to the configuration file.",
        ["Proxy.SecretStore"] = "the desktop secret service",

        ["Proxy.Validation.NameRequired"] = "Enter a name so you can recognise this proxy.",
        ["Proxy.Validation.NameDuplicate"] = "Another proxy already uses this name.",
        ["Proxy.Validation.HostRequired"] = "Enter the host name or IP address of the proxy.",
        ["Proxy.Validation.HostInvalid"] = "This is not a valid host name or IP address.",
        ["Proxy.Validation.PortRange"] = "Port must be between 1 and 65535.",

        // -- connections ----------------------------------------------------
        ["Connections.Route.Direct"] = "Direct",
        ["Connections.Route.Proxied"] = "Proxied",
        ["Connections.Route.Blocked"] = "Blocked",
        ["Connections.Route.Previous"] = "Previous route",
        ["Connections.Route.PreviousHint"] =
            "Opened before the rule was applied. Restart the application to move it onto the proxy.",

        // -- connections page -----------------------------------------------
        ["Connections.Title"] = "Connections",
        ["Connections.Subtitle"] = "What is flowing right now, and the route each connection is actually on.",
        ["Connections.SearchPlaceholder"] = "Search by process, destination or rule",
        ["Connections.Column.Process"] = "Process",
        ["Connections.Column.Destination"] = "Destination",
        ["Connections.Column.Protocol"] = "Proto",
        ["Connections.Column.Rule"] = "Matched rule",
        ["Connections.Column.Route"] = "Route",
        ["Connections.Column.State"] = "State",
        ["Connections.Column.Traffic"] = "Up / down",
        ["Connections.Column.Age"] = "Age",
        ["Connections.Count"] = "{0} connections",
        ["Connections.Empty"] = "No connections to show.",
        ["Connections.EmptyHint"] = "Connections appear here as processes open them.",
        ["Connections.NeedsDaemon"] = "Only the daemon can attribute connections to processes.",
        ["Connections.FilteredTo"] = "Showing only {0}",
        ["Connections.ClearFilter"] = "Show all processes",
        ["Connections.CreateRule"] = "Create a rule from this connection",
        ["Connections.DraftCreated"] = "A rule was drafted from this connection. Choose an action on the Rules page.",

        // -- rules page -----------------------------------------------------
        ["Rules.Title"] = "Rules",
        ["Rules.Subtitle"] = "One ordered list. The first rule that matches a connection decides it.",
        ["Rules.Count"] = "{0} rules",
        ["Rules.Empty"] = "No rules yet.",
        ["Rules.EmptyHint"] = "Select a process, start a game boost, or add a rule here.",
        ["Rules.SelectToInspect"] = "Select a rule to see what it matches, reorder it, or edit it.",
        ["Describe.AnyProcess"] = "Any process",
        ["Describe.AnyDestination"] = "Any destination",
        ["Describe.Instance"] = "Instance {0}",
        ["Describe.Path"] = "Path {0}",
        ["Describe.Name"] = "Name {0}",
        ["Describe.User"] = "User {0}",
        ["Describe.Port"] = "port {0}",
        ["Describe.WineTarget"] = "Wine target {0}",
        ["Describe.AndChildren"] = "and its children",
        ["Describe.Direct"] = "Direct",
        ["Describe.Block"] = "Block",
        ["Describe.Via"] = "via {0}",

        ["Rules.Column.Order"] = "#",
        ["Rules.Column.Name"] = "Rule",
        ["Rules.Column.Process"] = "Process",
        ["Rules.Column.Destination"] = "Destination",
        ["Rules.Column.Action"] = "Action",
        ["Rules.Column.State"] = "State",
        ["Rules.Column.Origin"] = "Created by",
        ["Rules.Origin.Manual"] = "Rules page",
        ["Rules.Origin.ProcessSelection"] = "Process selection",
        ["Rules.Origin.GameProfile"] = "Game profile",
        ["Rules.Origin.System"] = "Built in",
        ["Rules.Lifetime.Persistent"] = "Saved",
        ["Rules.Lifetime.Instance"] = "This instance",
        ["Rules.Lifetime.Session"] = "This session",
        ["Rules.State.Active"] = "Active",
        ["Rules.State.Pending"] = "Pending",
        ["Rules.State.Disabled"] = "Disabled",
        ["Rules.UnknownRoute"] = "Route missing",
        ["Rules.MoveEarlier"] = "Move up",
        ["Rules.MoveLater"] = "Move down",
        ["Rules.Enable"] = "Enable",
        ["Rules.Disable"] = "Disable",
        ["Rules.Disabled"] = "The rule was disabled and removed from the kernel.",
        ["Rules.Removed"] = "The rule was removed.",
        ["Rules.Applied"] = "“{0}” is active for new connections.",
        ["Rules.UndoAvailable"] = "Changed “{0}”.",
        ["Rules.UndoDone"] = "The change was undone.",
        ["Rules.Precedence"] = "Rules are evaluated top to bottom. Process selections sit above game profiles, which sit above rules added here.",
        ["Rules.Editor.TitleNew"] = "Add rule",
        ["Rules.Editor.TitleEdit"] = "Edit rule",
        ["Rules.Editor.Match"] = "Match",
        ["Rules.Editor.ProcessKind"] = "Process",
        ["Rules.Editor.ProcessName"] = "Process name",
        ["Rules.Editor.ExecutablePath"] = "Executable path",
        ["Rules.Editor.AnyProcess"] = "Any process",
        ["Rules.Editor.Destination"] = "Destination",
        ["Rules.Editor.Hosts"] = "Host names",
        ["Rules.Editor.HostsPlaceholder"] = "*.example.com, cdn.example.net",
        ["Rules.Editor.Networks"] = "Addresses",
        ["Rules.Editor.NetworksPlaceholder"] = "10.0.0.0/8, 203.0.113.9",
        ["Rules.Editor.Ports"] = "Ports",
        ["Rules.Editor.PortsPlaceholder"] = "443, 27000-27100",
        ["Rules.Editor.Action"] = "Action",
        ["Rules.Editor.Route"] = "Route",
        ["Rules.Editor.IncludeChildren"] = "Include child processes",
        ["Rules.Editor.NameRequired"] = "Give the rule a name you will recognise later.",
        ["Rules.Editor.ProcessRequired"] = "Enter the process name or executable path to match.",
        ["Rules.Editor.RouteRequired"] = "Choose which proxy or chain to route through.",
        ["Rules.Editor.BadNetwork"] = "“{0}” is not an address or CIDR range.",
        ["Rules.Editor.BadPort"] = "“{0}” is not a port or port range.",
        ["Rules.Editor.TooBroad"] = "A rule with no process and no destination would capture everything, including Yura's own traffic. Narrow it.",
        ["Rules.Editor.HostNeedsProcess"] = "A host-name rule needs a process to match: names are only visible once a connection is captured.",

        // -- diagnostics page -----------------------------------------------
        ["Diagnostics.Title"] = "Diagnostics",
        ["Diagnostics.Subtitle"] = "What the daemon found on this machine, and what it installed.",
        ["Diagnostics.Environment"] = "Environment",
        ["Diagnostics.Checks"] = "Startup checks",
        ["Diagnostics.Ok"] = "OK",
        ["Diagnostics.Failed"] = "Failed",
        ["Diagnostics.App"] = "Application",
        ["Diagnostics.Daemon"] = "Daemon",
        ["Diagnostics.Kernel"] = "Kernel",
        ["Diagnostics.Nftables"] = "nftables",
        ["Diagnostics.Uptime"] = "Daemon uptime",
        ["Diagnostics.Watcher"] = "Process tracking",
        ["Diagnostics.WatcherPollingHint"] = "Process events are unavailable, so membership is polled. A process that starts and connects within one interval keeps its original route.",
        ["Diagnostics.Counts"] = "Rules / flows / groups",
        ["Diagnostics.Socket"] = "Control socket",
        ["Diagnostics.AllowedUids"] = "Permitted users",
        ["Diagnostics.Config"] = "Configuration file",
        ["Diagnostics.Secrets"] = "Password storage",
        ["Diagnostics.SecretsInMemory"] = "this session only (no secret service found)",
        ["Diagnostics.Ruleset"] = "Installed ruleset",
        ["Diagnostics.LoadRuleset"] = "Show installed ruleset",
        ["Diagnostics.RulesetUnavailable"] = "The daemon is not running, so nothing is installed.",
        ["Diagnostics.Log"] = "Recent daemon log",
        ["Diagnostics.CopyReport"] = "Copy diagnostic report",
        ["Diagnostics.Copied"] = "The report was copied to the clipboard.",
        ["Diagnostics.ChecksFailed"] = "Some startup checks failed. Routing may not work until they are resolved.",

        // -- settings page --------------------------------------------------
        ["Settings.Title"] = "Settings",
        ["Settings.Subtitle"] = "Appearance, language and the one networking policy that applies to every rule.",
        ["Settings.Appearance"] = "Appearance",
        ["Settings.DarkTheme"] = "Dark theme",
        ["Settings.Chinese"] = "简体中文",
        ["Settings.ReducedMotion"] = "Reduce motion",
        ["Settings.ReducedMotionHint"] = "Removes transitions entirely rather than shortening them.",
        ["Settings.Processes"] = "Processes",
        ["Settings.ShowAllProcesses"] = "Show processes owned by other users",
        ["Settings.ShowAllProcessesHint"] = "System and root processes are hidden by default, because they are rarely what you want to route.",
        ["Settings.Networking"] = "Networking",
        ["Settings.Dns"] = "DNS for proxied processes",
        ["Settings.Dns.ThroughProxy"] = "Resolve through the proxy",
        ["Settings.Dns.Direct"] = "Resolve directly",
        ["Settings.Dns.ThroughProxyHint"] = "Name lookups from proxied processes go through the proxy, so the proxy's view of the network is the one the application sees and lookups do not reveal the destination locally.",
        ["Settings.Dns.DirectHint"] = "Name lookups leave directly. Faster, and works with a local resolver, but the destination is visible to whoever answers the lookup.",
        ["Settings.Storage"] = "Storage",
        ["Settings.OpenConfig"] = "Open configuration folder",
        ["Settings.OpenFailed"] = "Could not open the folder. The path is shown above.",
        ["Settings.Applied"] = "Saved and applied.",
        ["Settings.SavedNotApplied"] = "Saved. It will apply when the daemon connects.",

        // -- games additions ------------------------------------------------
        ["Games.Measure"] = "Measure",
        ["Games.MeasureTarget"] = "Measurement target",
        ["Games.MeasureTargetPlaceholder"] = "host:port of the game server",
        ["Games.MeasureTargetHint"] = "A game's server is only known once it connects. Take it from the Connections page, or type it.",
        ["Games.MeasureMethod"] = "Measured by",
        ["Games.MeasureFailed"] = "The measurement could not be completed.",
        ["Games.BadTarget"] = "Enter the target as host:port.",
        ["Games.Launch"] = "Launch",
        ["Games.Launching"] = "Asking Steam to start the game…",
        ["Games.LaunchFailed"] = "Could not ask Steam to start the game.",
        ["Games.Rescan"] = "Rescan library",
        ["Games.RescanFound"] = "{0} new game(s) found.",
        ["Games.RescanNoneNew"] = "No new games found.",
        ["Games.Added"] = "“{0}” was added from the running process.",
        ["Games.Attach"] = "Attach to running process",
        ["Games.AttachedTo"] = "Attached to {0} (pid {1})",
        ["Games.SteamNotStarted"] = "Steam app {0} — not running",
        ["Games.NotStarted"] = "Not running",
        ["Games.StartItFirst"] = "Start the game, then attach to it so Yura knows what to match.",
        ["Games.RuleName"] = "{0} (game boost)",
        ["Games.Started"] = "Boost started. New connections from the game use the selected route.",
        ["Games.StartedWithExisting"] = "Boost started. {0} connection(s) were already open and keep their previous route until the game reconnects.",
        ["Games.Stopped"] = "Boost stopped.",
        ["Games.AddFromProcess"] = "Add a running process as a game",

        // -- processes additions --------------------------------------------
        ["Processes.Action.AddAsGame"] = "Add as a game",
        ["Processes.Scope.ExcludeHint"] = "Children are moved out of the rule as soon as the kernel reports them. One that connects in its first instant can still use the parent's route.",
        ["Processes.RulesCovering"] = "Rules covering this process",
    };

    private static readonly Dictionary<string, string> ZhHans = new(StringComparer.Ordinal)
    {
        ["App.Name"] = "Yura",
        ["Nav.Processes"] = "进程",
        ["Nav.Games"] = "游戏",
        ["Nav.Connections"] = "连接",
        ["Nav.Proxies"] = "代理",
        ["Nav.Rules"] = "规则",
        ["Nav.Diagnostics"] = "诊断",
        ["Nav.Settings"] = "设置",
        ["Shell.DaemonConnected"] = "守护进程已连接",
        ["Shell.DaemonDisconnected"] = "守护进程未连接",
        ["Shell.DaemonDisconnectedDetail"] = "守护进程运行前无法应用路由更改。",
        ["Shell.Reconnect"] = "重新连接",

        ["Common.Apply"] = "应用",
        ["Common.Cancel"] = "取消",
        ["Common.Save"] = "保存",
        ["Common.Close"] = "关闭",
        ["Common.Refresh"] = "刷新",
        ["Common.Search"] = "搜索",
        ["Common.Remove"] = "移除",
        ["Common.Undo"] = "撤销",
        ["Common.Test"] = "测试",
        ["Common.Details"] = "技术细节",
        ["Common.Copy"] = "复制",
        ["Common.Unavailable"] = "不可用",
        ["Common.NotMeasured"] = "未测量",
        ["Common.Unknown"] = "未知",
        ["Common.Pending"] = "等待中",
        ["Common.Loading"] = "加载中…",
        ["Common.Pause"] = "暂停更新",
        ["Common.Resume"] = "恢复更新",
        ["Common.Paused"] = "更新已暂停",

        ["Processes.Title"] = "进程",
        ["Processes.Subtitle"] = "选择正在运行的应用程序，并将其流量通过代理转发。",
        ["Processes.SearchPlaceholder"] = "按名称、路径、PID 或用户搜索",
        ["Processes.TreeView"] = "进程树",
        ["Processes.FlatView"] = "平铺列表",
        ["Processes.ShowSystem"] = "包含系统进程",
        ["Processes.Column.Process"] = "进程",
        ["Processes.Column.Pid"] = "PID",
        ["Processes.Column.User"] = "用户",
        ["Processes.Column.Path"] = "可执行文件路径",
        ["Processes.Column.Parent"] = "父进程",
        ["Processes.Column.Policy"] = "路由策略",
        ["Processes.Column.Connections"] = "连接数",
        ["Processes.Empty"] = "没有符合此筛选条件的进程。",
        ["Processes.EmptyHint"] = "请清除搜索框，或包含系统进程。",
        ["Processes.Selected"] = "已选择 {0} 项",
        ["Processes.LiveSorting"] = "实时排序",
        ["Processes.Count"] = "{0} 个进程",
        ["Processes.CountFiltered"] = "{0} / {1} 个进程",

        ["Processes.Action.ProxyInstance"] = "代理此实例",
        ["Processes.Action.AlwaysProxy"] = "始终代理此可执行文件",
        ["Processes.Action.Direct"] = "直接连接",
        ["Processes.Action.Block"] = "阻止网络访问",
        ["Processes.Action.RemoveOverride"] = "移除临时覆盖",
        ["Processes.Action.IncludeChildren"] = "包含子进程",
        ["Processes.Action.InspectConnections"] = "查看连接",

        ["Processes.Scope.Title"] = "规则范围",
        ["Processes.Scope.Instance"] = "此运行实例",
        ["Processes.Scope.InstanceHint"] = "该进程退出后规则失效。重用的 PID 不会继承此策略。",
        ["Processes.Scope.Executable"] = "此可执行文件的后续实例",
        ["Processes.Scope.ExecutableHint"] = "已保存，此路径再次运行时会重新应用。",
        ["Processes.Scope.Tree"] = "此进程及其子进程",
        ["Processes.Scope.TreeHint"] = "新建子进程会被覆盖。已有子进程保持当前路由。",

        ["Processes.Inspector.Identity"] = "标识",
        ["Processes.Inspector.Policy"] = "当前策略",
        ["Processes.Inspector.Connections"] = "活动连接",
        ["Processes.Inspector.Actions"] = "操作",
        ["Processes.Inspector.Route"] = "路由至",
        ["Processes.Inspector.NoSelection"] = "选择一个进程以查看详情。",
        ["Processes.Inspector.StartTime"] = "启动于",
        ["Processes.Inspector.Cgroup"] = "控制组",
        ["Processes.Inspector.WineTarget"] = "Wine 目标",

        ["Processes.Policy.Direct"] = "直连",
        ["Processes.Policy.Blocked"] = "已阻止",
        ["Processes.Policy.Proxied"] = "已代理",
        ["Processes.Policy.PendingApply"] = "正在应用…",
        ["Processes.Policy.NewConnectionsOnly"] = "仅新建连接",

        ["Processes.Applied.Title"] = "规则已对新连接生效",
        ["Processes.Applied.Body"] = "此后建立的连接将使用 {0}。已经打开的连接在应用程序重新连接之前仍使用原有路由。",
        ["Processes.PathDenied"] = "权限不足",
        ["Processes.PathDeleted"] = "启动后可执行文件已被替换",

        ["Games.Title"] = "游戏",
        ["Games.Subtitle"] = "选择游戏，选定线路，然后开始加速。",
        ["Games.SelectGame"] = "游戏",
        ["Games.SelectRoute"] = "线路",
        ["Games.StartBoost"] = "开始加速",
        ["Games.StopBoost"] = "停止加速",
        ["Games.Comparison"] = "直连与代理对比",
        ["Games.Direct"] = "直连",
        ["Games.Routed"] = "代理",
        ["Games.Latency"] = "延迟",
        ["Games.Jitter"] = "抖动",
        ["Games.Loss"] = "丢包率",
        ["Games.MeasurementTarget"] = "测量目标",
        ["Games.LastUpdate"] = "最后更新",
        ["Games.SessionDuration"] = "会话时长",
        ["Games.Compatibility"] = "传输协议支持",
        ["Games.TcpSupported"] = "支持 TCP",
        ["Games.UdpSupported"] = "支持 UDP",
        ["Games.UdpUnsupported"] = "不支持 UDP",
        ["Games.UdpUnknown"] = "UDP 未测量",
        ["Games.UdpWarning"] = "此代理无法转发 UDP。使用 UDP 的游戏将不会被加速。",
        ["Games.NoGames"] = "尚未检测到游戏。",
        ["Games.NoGamesHint"] = "可手动添加游戏，或启动游戏后它会显示在此处。",

        ["Games.SessionState"] = "会话状态",
        ["Games.State.Ready"] = "就绪",
        ["Games.State.Testing"] = "测试中",
        ["Games.State.Starting"] = "启动中",
        ["Games.State.WaitingForGame"] = "等待游戏",
        ["Games.State.Routing"] = "加速中",
        ["Games.State.Degraded"] = "质量下降",
        ["Games.State.Stopping"] = "正在停止",
        ["Games.State.Failed"] = "失败",

        ["Proxy.Editor.TitleNew"] = "添加代理",
        ["Proxy.Editor.TitleEdit"] = "编辑代理",
        ["Proxy.Name"] = "显示名称",
        ["Proxy.NamePlaceholder"] = "家庭服务器",
        ["Proxy.Protocol"] = "协议",
        ["Proxy.Host"] = "主机",
        ["Proxy.HostPlaceholder"] = "127.0.0.1 或 proxy.example.com",
        ["Proxy.Port"] = "端口",
        ["Proxy.Username"] = "用户名",
        ["Proxy.Password"] = "密码",
        ["Proxy.Optional"] = "可选",
        ["Proxy.Advanced"] = "高级选项",
        ["Proxy.AdvancedHint"] = "超时、TLS 校验与 UDP 行为。",
        ["Proxy.TestConnection"] = "测试连接",
        ["Proxy.Testing"] = "测试中…",
        ["Proxy.TestPassed"] = "可达，用时 {0} 毫秒",
        ["Proxy.TestFailed"] = "无法连接到代理",
        ["Proxy.Hint"] = "Yura 不会为你运行代理，请指向你已在运行的代理。",
        ["Proxy.SecretHint"] = "密码保存在{0}，不会写入配置文件。",
        ["Proxy.SecretHintUnavailable"] = "未找到桌面密钥服务，密码仅在本次会话中保留，且不会写入配置文件。",
        ["Proxy.SecretStore"] = "桌面密钥服务",

        ["Proxy.Validation.NameRequired"] = "请输入名称，以便识别此代理。",
        ["Proxy.Validation.NameDuplicate"] = "已有同名代理。",
        ["Proxy.Validation.HostRequired"] = "请输入代理的主机名或 IP 地址。",
        ["Proxy.Validation.HostInvalid"] = "这不是有效的主机名或 IP 地址。",
        ["Proxy.Validation.PortRange"] = "端口必须介于 1 与 65535 之间。",

        ["Connections.Route.Direct"] = "直连",
        ["Connections.Route.Proxied"] = "已代理",
        ["Connections.Route.Blocked"] = "已阻止",
        ["Connections.Route.Previous"] = "原有路由",
        ["Connections.Route.PreviousHint"] = "在规则应用之前建立。重启应用程序即可改用代理。",

        ["Connections.Title"] = "连接",
        ["Connections.Subtitle"] = "当前正在传输的流量，以及每个连接实际使用的路由。",
        ["Connections.SearchPlaceholder"] = "按进程、目标或规则搜索",
        ["Connections.Column.Process"] = "进程",
        ["Connections.Column.Destination"] = "目标",
        ["Connections.Column.Protocol"] = "协议",
        ["Connections.Column.Rule"] = "匹配的规则",
        ["Connections.Column.Route"] = "路由",
        ["Connections.Column.State"] = "状态",
        ["Connections.Column.Traffic"] = "上行 / 下行",
        ["Connections.Column.Age"] = "时长",
        ["Connections.Count"] = "{0} 个连接",
        ["Connections.Empty"] = "没有可显示的连接。",
        ["Connections.EmptyHint"] = "进程建立连接后会显示在此处。",
        ["Connections.NeedsDaemon"] = "只有守护进程能将连接归属到具体进程。",
        ["Connections.FilteredTo"] = "仅显示 {0}",
        ["Connections.ClearFilter"] = "显示所有进程",
        ["Connections.CreateRule"] = "根据此连接创建规则",
        ["Connections.DraftCreated"] = "已根据此连接起草规则，请在“规则”页面选择动作。",

        ["Rules.Title"] = "规则",
        ["Rules.Subtitle"] = "一份有序列表。第一条匹配的规则决定该连接。",
        ["Rules.Count"] = "{0} 条规则",
        ["Rules.Empty"] = "暂无规则。",
        ["Rules.EmptyHint"] = "可选择进程、启动游戏加速，或在此添加规则。",
        ["Rules.SelectToInspect"] = "选择一条规则，即可查看其匹配条件、调整顺序或进行编辑。",
        ["Describe.AnyProcess"] = "任意进程",
        ["Describe.AnyDestination"] = "任意目标",
        ["Describe.Instance"] = "实例 {0}",
        ["Describe.Path"] = "路径 {0}",
        ["Describe.Name"] = "名称 {0}",
        ["Describe.User"] = "用户 {0}",
        ["Describe.Port"] = "端口 {0}",
        ["Describe.WineTarget"] = "Wine 目标 {0}",
        ["Describe.AndChildren"] = "及其子进程",
        ["Describe.Direct"] = "直连",
        ["Describe.Block"] = "阻止",
        ["Describe.Via"] = "经由 {0}",

        ["Rules.Column.Order"] = "#",
        ["Rules.Column.Name"] = "规则",
        ["Rules.Column.Process"] = "进程",
        ["Rules.Column.Destination"] = "目标",
        ["Rules.Column.Action"] = "动作",
        ["Rules.Column.State"] = "状态",
        ["Rules.Column.Origin"] = "创建来源",
        ["Rules.Origin.Manual"] = "规则页面",
        ["Rules.Origin.ProcessSelection"] = "进程选择",
        ["Rules.Origin.GameProfile"] = "游戏配置",
        ["Rules.Origin.System"] = "内置",
        ["Rules.Lifetime.Persistent"] = "已保存",
        ["Rules.Lifetime.Instance"] = "此实例",
        ["Rules.Lifetime.Session"] = "本次会话",
        ["Rules.State.Active"] = "生效中",
        ["Rules.State.Pending"] = "等待中",
        ["Rules.State.Disabled"] = "已停用",
        ["Rules.UnknownRoute"] = "线路缺失",
        ["Rules.MoveEarlier"] = "上移",
        ["Rules.MoveLater"] = "下移",
        ["Rules.Enable"] = "启用",
        ["Rules.Disable"] = "停用",
        ["Rules.Disabled"] = "规则已停用，并从内核中移除。",
        ["Rules.Removed"] = "规则已移除。",
        ["Rules.Applied"] = "“{0}”已对新建连接生效。",
        ["Rules.UndoAvailable"] = "已更改“{0}”。",
        ["Rules.UndoDone"] = "更改已撤销。",
        ["Rules.Precedence"] = "规则自上而下求值。进程选择优先于游戏配置，游戏配置优先于在此添加的规则。",
        ["Rules.Editor.TitleNew"] = "添加规则",
        ["Rules.Editor.TitleEdit"] = "编辑规则",
        ["Rules.Editor.Match"] = "匹配条件",
        ["Rules.Editor.ProcessKind"] = "进程",
        ["Rules.Editor.ProcessName"] = "进程名称",
        ["Rules.Editor.ExecutablePath"] = "可执行文件路径",
        ["Rules.Editor.AnyProcess"] = "任意进程",
        ["Rules.Editor.Destination"] = "目标",
        ["Rules.Editor.Hosts"] = "主机名",
        ["Rules.Editor.HostsPlaceholder"] = "*.example.com, cdn.example.net",
        ["Rules.Editor.Networks"] = "地址",
        ["Rules.Editor.NetworksPlaceholder"] = "10.0.0.0/8, 203.0.113.9",
        ["Rules.Editor.Ports"] = "端口",
        ["Rules.Editor.PortsPlaceholder"] = "443, 27000-27100",
        ["Rules.Editor.Action"] = "动作",
        ["Rules.Editor.Route"] = "线路",
        ["Rules.Editor.IncludeChildren"] = "包含子进程",
        ["Rules.Editor.NameRequired"] = "请为规则取一个便于日后识别的名称。",
        ["Rules.Editor.ProcessRequired"] = "请输入要匹配的进程名称或可执行文件路径。",
        ["Rules.Editor.RouteRequired"] = "请选择要经过的代理或代理链。",
        ["Rules.Editor.BadNetwork"] = "“{0}”不是有效的地址或 CIDR 网段。",
        ["Rules.Editor.BadPort"] = "“{0}”不是有效的端口或端口范围。",
        ["Rules.Editor.TooBroad"] = "既不限定进程也不限定目标的规则会捕获全部流量，包括 Yura 自身的流量。请缩小范围。",
        ["Rules.Editor.HostNeedsProcess"] = "主机名规则需要指定进程：只有连接被捕获后才能看到名称。",

        ["Diagnostics.Title"] = "诊断",
        ["Diagnostics.Subtitle"] = "守护进程在本机的检测结果，以及已安装的内容。",
        ["Diagnostics.Environment"] = "运行环境",
        ["Diagnostics.Checks"] = "启动检查",
        ["Diagnostics.Ok"] = "正常",
        ["Diagnostics.Failed"] = "失败",
        ["Diagnostics.App"] = "应用程序",
        ["Diagnostics.Daemon"] = "守护进程",
        ["Diagnostics.Kernel"] = "内核",
        ["Diagnostics.Nftables"] = "nftables",
        ["Diagnostics.Uptime"] = "守护进程运行时长",
        ["Diagnostics.Watcher"] = "进程跟踪",
        ["Diagnostics.WatcherPollingHint"] = "进程事件不可用，只能轮询成员关系。在一个轮询间隔内启动并建立连接的进程会保持其原有路由。",
        ["Diagnostics.Counts"] = "规则 / 流 / 分组",
        ["Diagnostics.Socket"] = "控制套接字",
        ["Diagnostics.AllowedUids"] = "允许的用户",
        ["Diagnostics.Config"] = "配置文件",
        ["Diagnostics.Secrets"] = "密码存储",
        ["Diagnostics.SecretsInMemory"] = "仅本次会话（未找到密钥服务）",
        ["Diagnostics.Ruleset"] = "已安装的规则集",
        ["Diagnostics.LoadRuleset"] = "显示已安装的规则集",
        ["Diagnostics.RulesetUnavailable"] = "守护进程未运行，因此未安装任何内容。",
        ["Diagnostics.Log"] = "近期守护进程日志",
        ["Diagnostics.CopyReport"] = "复制诊断报告",
        ["Diagnostics.Copied"] = "报告已复制到剪贴板。",
        ["Diagnostics.ChecksFailed"] = "部分启动检查失败。在解决之前路由可能无法工作。",

        ["Settings.Title"] = "设置",
        ["Settings.Subtitle"] = "外观、语言，以及对所有规则生效的那项网络策略。",
        ["Settings.Appearance"] = "外观",
        ["Settings.DarkTheme"] = "深色主题",
        ["Settings.Chinese"] = "简体中文",
        ["Settings.ReducedMotion"] = "减少动态效果",
        ["Settings.ReducedMotionHint"] = "完全移除过渡效果，而非仅缩短时长。",
        ["Settings.Processes"] = "进程",
        ["Settings.ShowAllProcesses"] = "显示其他用户的进程",
        ["Settings.ShowAllProcessesHint"] = "默认隐藏系统与 root 进程，因为通常不需要为它们设置路由。",
        ["Settings.Networking"] = "网络",
        ["Settings.Dns"] = "被代理进程的 DNS",
        ["Settings.Dns.ThroughProxy"] = "通过代理解析",
        ["Settings.Dns.Direct"] = "直接解析",
        ["Settings.Dns.ThroughProxyHint"] = "被代理进程的域名解析经由代理，因此应用看到的网络视图与代理一致，解析过程也不会在本地暴露目标。",
        ["Settings.Dns.DirectHint"] = "域名解析直接发出。速度更快且可使用本地解析器，但应答方能看到目标域名。",
        ["Settings.Storage"] = "存储",
        ["Settings.OpenConfig"] = "打开配置文件夹",
        ["Settings.OpenFailed"] = "无法打开文件夹，路径见上方。",
        ["Settings.Applied"] = "已保存并应用。",
        ["Settings.SavedNotApplied"] = "已保存，将在守护进程连接后应用。",

        ["Games.Measure"] = "测量",
        ["Games.MeasureTarget"] = "测量目标",
        ["Games.MeasureTargetPlaceholder"] = "游戏服务器的 主机:端口",
        ["Games.MeasureTargetHint"] = "只有游戏建立连接后才能知道其服务器。可从“连接”页面获取，或手动输入。",
        ["Games.MeasureMethod"] = "测量方式",
        ["Games.MeasureFailed"] = "测量未能完成。",
        ["Games.BadTarget"] = "请按 主机:端口 的格式输入目标。",
        ["Games.Launch"] = "启动",
        ["Games.Launching"] = "正在请求 Steam 启动游戏…",
        ["Games.LaunchFailed"] = "无法请求 Steam 启动游戏。",
        ["Games.Rescan"] = "重新扫描库",
        ["Games.RescanFound"] = "发现 {0} 个新游戏。",
        ["Games.RescanNoneNew"] = "未发现新游戏。",
        ["Games.Added"] = "已从运行中的进程添加“{0}”。",
        ["Games.Attach"] = "附加到运行中的进程",
        ["Games.AttachedTo"] = "已附加到 {0}（PID {1}）",
        ["Games.SteamNotStarted"] = "Steam 应用 {0} — 未运行",
        ["Games.NotStarted"] = "未运行",
        ["Games.StartItFirst"] = "请先启动游戏并附加，Yura 才知道要匹配什么。",
        ["Games.RuleName"] = "{0}（游戏加速）",
        ["Games.Started"] = "加速已开始。游戏新建的连接将使用所选线路。",
        ["Games.StartedWithExisting"] = "加速已开始。已有 {0} 个连接处于打开状态，在游戏重新连接前仍使用原有路由。",
        ["Games.Stopped"] = "加速已停止。",
        ["Games.AddFromProcess"] = "将运行中的进程添加为游戏",

        ["Processes.Action.AddAsGame"] = "添加为游戏",
        ["Processes.Scope.ExcludeHint"] = "内核报告子进程后会立即将其移出规则。在创建瞬间就建立连接的子进程仍可能使用父进程的路由。",
        ["Processes.RulesCovering"] = "覆盖此进程的规则",
    };
}
